spring:
  profiles:
    active: @spring.profiles.active@
  liquibase:
    change-log: classpath:database-changelog.yml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  activemq:
    broker-url: tcp://localhost:61616
    packages:
      trust-all: true
    in-memory: true
    user: admin
    password: admin

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:./h2-database
#    url: jdbc:h2:mem:database
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
    settings:
      web-allow-others: true

---
spring:
  config:
    activate:
      on-profile: cloud
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver