spring:
  profiles:
    active: @spring.profiles.active@
  liquibase:
    change-log: classpath:database-changelog.yml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
    settings:
      web-allow-others: true

---
spring:
  config:
    activate:
      on-profile: cloud
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect